- nais-dev.yaml
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/App.kt
Har lagt til Naiserator-manifest, og appen starter fint på Nais. Så lenge man midlertidig deaktiverer Kafka-oppsettet, som ikke er satt opp enda.
* Appen er nå satt opp i Vault, og det er lagt til en dummy secret som leses inn av appen for å demonstrere at dette fungerer.
* Det er også demonstrert at ikke sensitive properties definert i nais.yaml kan leses inn av appen.
* Byttet til ny ingress under dev-sbs.nais.io.
PB-88. Kjøre på Naiserator
> Appen kjører på Naiserator og kan hente fra Vault

- nais-dev.yaml
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/App.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/Consumer.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/Producer.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/api/Produce.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Config.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Environment.kt
* Konfigurert appen til å koble seg til Kafka i preprod.
* Appen lytter på en informasjon-topic.
* Har et midlertidig endepunkt som gjør at man kan produsere et nytt informasjon-event, som man kan se at appen leser inn igjen fra Kafka.
PB-93. Koble DEA mot NAVs Kafka-instans
> Koble opp mot NAVs Kafka-instans

- build.gradle.kts
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/App.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/api/Health.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/api/Produce.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Kafka.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/KafkaConsumerSetup.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Server.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/kafka/Consumer.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/kafka/Producer.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/service/EventBatchProcessorService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/service/impl/EventToConsoleBatchProcessorService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/service/impl/InformasjonEventService.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/database/entity/InformasjonObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/database/entity/InformasjonQueriesTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/kafka/BasicKafkaEmbeddedTesting.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/kafka/BasicKafkaEmbeddedTestingIT.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/kafka/ConsumerTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/kafka/MultipleTopicsConsumerIT.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/kafka/SingleTopicConsumerIT.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/schema/objectmother/InformasjonObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/schema/objectmother/MeldingObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/schema/objectmother/OppgaveObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/service/impl/SimpleEventCounterService.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/util/KafkaConsumerUtil.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/util/KafkaProducerUtil.kt
- src/test/resources/logback.xml
* Appen kjører nå i test og lytter på topic-ene Informasjon, Oppgave og Melding i parallell. Har også opprettet integrasjonstester som verifiserer at alt fungerer.
Topic-ene for BrukernotifikasjonDone og Statusoppdatering legges til i egne features.
PB-139. Lytte på alle våre event-topics
> Appen er klargjort for å lytte på flere topics i parallell

- README.md
- build.gradle.kts
- docker-compose.yml
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/api/health.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Bootstrap.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveEventService.kt
PB-199. Forenkle lokal testing med sikkerhet aktivert
> Mindre justeringer ifm docker-compose-oppsettet

- .circleci/config.yml
Latest-tagging på Dockerhub kun hvis det er trigget fra master-branchen.
> Pb 304 latest master

- build.gradle.kts
- src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/util/KafkaTestUtil.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/ApplicationContext.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Environment.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Flyway.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/PostgresDatabase.kt
Default-verdiene som brukes ved lokal kjøring er flyttet ut til å bli satt i build.gradle.kts (se runServer).
PB-375. Alle apper skal stoppe hvis konfig mangler
> Appen vil nå stoppe hvis ikke alle miljøvariabler er satt.

- Dockerfile
- init.sh
- nais/dev-sbs/q1.json
- nais/nais.yaml
- nais/prod-sbs/default.json
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Environment.kt
PB-377. Opprette tabeller i databasen i prod
> Setter opp appen til å lese inn systembrukeren automatisk fra Vault.

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Environment.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/KafkaConsumerSetup.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/bootstrap.kt
This reverts commit 5a6ea906cf2a0e843d896f739a293f5f842d3dcd.
> Revert "Gjør det midlertidig slik at appen ikke bruker Kafka i prod."

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/ApplicationContext.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/KafkaConsumerSetup.kt
Gjort slik at mest mulig er tilgjengelig fra klassen ApplicationContext, slik at flest mulig instanser er tilgjengelige fra et sted.
> Ryddet i instansieringen objektene som appen bruker under kjøring.

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/KafkaConsumerSetup.kt
This reverts commit 1251da3b34c29678beb2576d678b4e3aa7f09371.
> Revert "Skru av polling for beskjed middlertidig."

- nais/prod-sbs/default.json
Legger inn en nais.io ingress for prod.
> Legger inn nais.io ingress

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/Consumer.kt
Vi har sett noen feil som kan tyde på at vi comitter mot Kafka selv om eventer ikke har blitt skrevet korrekt til basen. I et forsøk på å være helt sikre på at koden oppfører seg som vi tror legges withContext rundt hele "transaksjonen".
> Legger withContext rundt hele sløyfen som leser fra Kafka og comitter hvis alt gikk bra

- src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/ConsumerTestIT.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/Consumer.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/ConsumerTest.kt
Denne endringen skal reverteres på et senere tidspunkt.
> Ønsker midlertidig at all polling stoppes ved alle typer feil

- src/main/resources/db/migration/V1.1.5__Legger_paa_indekser_fodselsnummer_aktiv.sql
Ref. diskusjon i #postgres på Slack
> Legger på ny indeks for fodselsnummer og aktiv.

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/EventMetricsSession.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveEventService.kt
Slik at det er lettere å følge med i loggene på om det er en eller flere produsenter som gjør dette.
> La til logging av hvilken produsent det er som har sendt duplikat-eventer

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/EventBatchProcessorService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/StatusoppdateringEventService.kt
Forslag til løsning av dette https://github.com/navikt/dittnav-varselbestiller/pull/6#discussion_r508274393.
Usikker, så tar gjerne forslag til andre løsninger :)
> Fjerner funksjonskall som kan kaste ny exception fra catch-blokker.

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/Oppgave.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveTest.kt
Ref. https://github.com/navikt/brukernotifikasjon-schemas/pull/21#discussion_r535999628
> Gjør link obligatorisk for Oppgave.

- nais/dev-sbs/personbruker.json
- nais/prod-sbs/default.json
Bytter deprekert oera-q ingress med dev.nav ingress.
> Pb 578 ingresser

- nais/dev-sbs/nais.yaml
- nais/prod-sbs/nais.yaml
Legger til en egen nais.yaml per cluster.
> Gjør prosjektet foroverkompatibel med ny struktur uten template vars.

- nais/dev-gcp/nais.yaml
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Kafka.kt
- src/main/resources/db/migration/V1.1.11__Gir_handler_rettigheter.sql
Gir tilgang til brukeren opprettet her: https://github.com/navikt/dittnav-event-handler/pull/102
> Tilgang til tabeller for handlers les-bruker

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/polling/PeriodicConsumerPollingCheck.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/KafkaConsumerSetup.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/polling/PeriodicConsumerPollingCheckTest.kt
> Polling av Innboks i prod

- nais/dev-gcp/nais.yaml
- nais/prod-gcp/nais.yaml
Match justering i resurser for on-prem.
> Senker reserverte resurser basert på metrikker for reell bruk.

- src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/beskjedQueriesTest.kt
- src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/oppgaveQueriesTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/StatusoppdateringObjectMother.kt
Virker som alle repoene sliter med dette nå, kanskje fordi har oppdatert actions med java 17?
> Truncate datoer

- src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneRepositoryTest.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/beskjedQueries.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/entity/Brukernotifikasjon.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/expired/DoneEventEmitter.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/innboksQueries.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/oppgaveQueries.kt
Fjerner sjekken på systembruker når vi sammenlikner done med andre eventtyper.
Fikser dato-feil på done-eventer sendt fra done-emitter.
> Done uten systembruker

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/varsel/BeskjedSink.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedQueriesTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTransformerTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/archive/BeskjedArchivingQueriesTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/LocalDateTimeTestHelper.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/localDateTimeExt.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneTransformerTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/expired/ExpiredTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksQueriesTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksTransformerTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/archive/InnboksArchivingQueriesTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveObjectMother.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveQueriesTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveTransformerTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/archive/OppgaveArchivingQueriesTest.kt
Fikser potensielle feil med tidspresisjon ved å abstrahere vekk kall til LocalDateTime.now()
> Time crimes

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksEventService.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveEventService.kt
Appen skal være idempotent, trenger ikke gjøre noe ved duplikater.
Lager litt støy i loggene nå som vi samtidig leser fra rapid i dev
> Fjerne warning ved duplikate eventer

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/application.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusEnum.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternStatusOppdatering.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingOppdatertProducer.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatusSink.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatusUpdater.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/eksternVarslingStatusQueries.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneApi.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneSink.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/VarselInaktivertKilde.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/VarselInaktivertProducer.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/jobs/PeriodicDoneEventWaitingTableProcessor.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/expired/PeriodicExpiredVarselProcessor.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatusSinkTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneSinkTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/VarselInaktivertRapidProducerTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/expired/PeriodicExpiredVarselProcessorTest.kt
Legger til kilde for varsel inaktivert. Sender event når doknot status oppdateres.
> Utvid hendelser

- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingOppdatertProducer.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/VarselInaktivertProducer.kt
- src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/varsel/VarselAktivertProducer.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatusSinkTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/VarselInaktivertRapidProducerTest.kt
- src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/varsel/VarselAktivertProducerTest.kt
Leg ved opprettelsestidspunkt for utgpående eventer.
> Tidspunkt for output-eventer.
