src/intTest/resources/logback.xml, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/logging/MaskedLoggingEvent.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/logging/MaskedThrowableProxy.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/logging/MaskingAppender.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/logging/MaskedLoggingEventTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/logging/MaskedThrowableProxyTest.kt
* Dette sørger for at stacktraces vises riktig i Kibana.
* Lag til logge-filter som erstatter strenger som ligner på fødselsnummer med stjerner (***).
PB-357. Logback config
=> Lagt til oppdatert logback-konfig.

src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTeardownQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/entity/BrukernotifikasjonQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/CachedDoneEventConsumerTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneEventServiceTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveQueriesTest.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/Beskjed.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedRepository.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/ApplicationContext.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/CachedDoneEventConsumer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneBatchProcessor.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneRepository.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/Innboks.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksRepository.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/Oppgave.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveRepository.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedEventServiceTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneBatchProcessorTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksEventServiceTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveEventServiceTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveTest.kt
Hver gang det kommer inn et nytt done-event vil de bli forsøkt matchet opp mot aktive Beskjeder, Oppgaver eller Innboks-eventer. Hvis det skulle bli en bom, så havner eventet i ventetabellen. I prosesseringen av ventetabellen så vil det bli forsøkt å matches opp mot alle eventer, ikke kun de som er markert som aktive. Dette fører til at første gangsprosessering av done-eventer vil gå raskere.
PB-138. Ytelsestesting av DEA
=> Optimalisert ytelsen ved å i første omgang kun match-e done-eventer mot aktive brukernotifikasjoner

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/validation/validationUtil.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/AvroBeskjedObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTransformerTest.kt
Rettet feil som gjorde at det ikke lengre var gyldig å droppe å sette feltet synligFremTil.
Har lagt til en test som framprovoser feilen, slik at dette ikke oppstår igjen.
=> Gjort det tillatt å ikke spesifisere synligFremTil igjen

src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/CachedDoneEventConsumerTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveQueriesTest.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/exceptions/NokkelNullException.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/serializer/nullCheck.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/validation/validationUtil.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/Done.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneTransformer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveEventService.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/objectmother/BrukernotifikasjonObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/objectmother/ConsumerRecordsObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneEventServiceTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/schema/AvroDoneObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/nokkel/nokkelObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveTest.kt
* Lagt til prevalidering av feltene for done-eventer, slik at vi unngår feil mot databasen pga feltlengder.
* Lagt til full testdekning på behandlingen av done-eventer.
* I tilfeller hvor det skjer en NokkelNullException vil man ikke kunne hente ut en systembruker, fordi dette feltet ligger i Nokkel som jo ikke har noen verdi.
PB-390. Feilhåndtering hvis ett event i en batch ikke validerer
=> PB-390 - Prevalidering av Done-eventer

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/CachedDoneEventConsumer.kt
Dette gjøres for å nå i en periode lettere kunne følge med på hvordan det faktisk går med prosesseringen av done-eventer.
=> Logging av status etter prosessering av done-eventer

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/CachedDoneEventConsumer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneBatchProcessor.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/CachedDoneEventConsumerTest.kt
Rettet feilen som gjorde at databasen ikke ble oppdatert etter prosessering av inaktive-eventer. Dette førte til at done-eventer som det ble funnet match for, på eventer som alt var satt til inaktive, ikke ble fjernet fra done-tabellen.
Har implementert en test som verifiserer at databasen blir oppdatert både etter prosessering av aktive og inaktive eventer.
=> Del en av retting av at done-tabellen ikke blir tømt ved treff

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/entity/BrukernotifikasjonQueries.kt
Det kan se ut som det som egentlig skulle være en optimalisering (join on unnest) egentlig hadde negativ effekt på ytelse. Bytter ut med et mer rett frem "where in any"-clause
=> Byttet ut "join on unnest..." med "where in any..."

src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/ThrowingEventCounterService.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/util/KafkaTestUtil.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/ConsumerTestIT.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/Consumer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/kafkaConsumer.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/ConsumerTest.kt
Forsøk på å løse commit problemet vi hadde ved å flytte offset tilbake til den siste "trygge" verdien vi fikk fra kafka etter det har skjedd en periodisk feil, slik at vi kan prøve å lese herfra på nytt igjen.
=> Lagt til enkel lokal rollback for håndtering av periodiske feil.

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/CachedDoneEventConsumer.kt
=> Fjerner logging av cachet done-event-prosessering.

nais/nais.yaml
For å utelukke feil ifm at flere podder samarbeider.
=> Låser antall pods til å være en.

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/Consumer.kt
Hvis ikke blir det ikke logget, fordi coroutine-en har blitt avbrutt.
=> Loggingen må skje før selve coroutine-en stoppes

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/eventCountingApi.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/KafkaEventCounterService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/NumberOfUniqueKafkaRecords.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/UniqueKafkaEventIdentifier.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/kafkaCountingApi.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/kafkaCountingUtil.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/NumberOfUniqueKafkaRecordsTest.kt
På sikt kan denne koden erstatte den gamle tellekoden, men nå i første omgang legger jeg det bare til som et tillegg.
Ytelsen mellom den gamle og den nye implementasjonen ser veldig lik ut, men vil gjerne teste det i et miljø først.
=> Funksjonalitet for å telle unike eventer, duplikater og totalt antall eventer på en topic

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/Consumer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/pollingApi.kt
**Sørger for at alle kafka-pollere kjører etter at start-polling har blitt kalt.**
Tidligere kunne man risikere at de poller-ene som fortsatt kjørte, i det start-polling ble kalt, ville stoppe mens de som tidligere var stoppet ville starte. Slik ble tilstanden stadig flippet, med mindre man manuelt kalte stop-polling. Legger derfor heller til en eksplisitt stop-polling før alle kafka-pollere blir startet på nytt.
**Logger at det startes en ny coroutine for å prosessere en gitt topic.**
Dette skal typisk bare skje hvis pollingen har blitt stoppet, og vi manuelt starter det igjen. Det er også en fin måte å følge med på om det spinnes opp flere coroutiner enn tiltenkt for dette.
=> Gjør det enklere å starte kafka-pollerne igjen

nais/nais.yaml
PB-451. Sette opp metrics for eventer i databasen vs kafka
=> Aktiverer scraping av applikasjonens Prometheus-metrikker

build.gradle.kts, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/util/KafkaTestUtil.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/topic/TopicEventCounterServiceIT.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/kafkaConsumer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/ApplicationContext.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Environment.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Kafka.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/KafkaConsumerSetup.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/bootstrap.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/kafkaCountingUtil.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/topic/TopicEventCounterService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/submitter/PeriodicMetricsSubmitter.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/objectmother/ConsumerRecordsObjectMother.kt
* Gjøres for å roe ned antallet logginnslag ifm start og stop av kafkaklientene for event-telling.
* For å se om minneforbrukte blir mer stabilt.
* Øker frekvensen for innrapportering av periodiske metrics.
* Hardkoder groupId-en for teller-klientene per eventtype, for å være sikker på å ikke få samme groupId som de vanlige kafka-konsumerene.
=> Gjenbruker kafkaklientene som brukes for telling av eventer

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/ApplicationContext.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/topic/TopicEventCounterService.kt
Siden parameterene er av samme type var det mulig å sende inn feil, det førte til at for telling av oppgave-eventer så var det innboks-klienten som ble brukt.
=> Byttet til korrekt rekkefølge på parameterene inn til TopicEventCounterService

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Kafka.kt
Default-verdien er fem minutter, øker den til seks minutter siden tellinger gjøres hvert femte minutt. Slik at vi har litt slakk.
=> Øker det maksimale polle-intervallet for kafka-konsumerene som brukes for å telle eventer

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/Beskjed.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTransformerTest.kt
Beskjed-tekst limit er satt til 300.
Fyi, i prod er fortsatt den lengste beskjeden 290 tegn.
=> Endrer beskjed-tekst limit til 300

src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/topic/TopicEventCounterServiceIT.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/ApplicationContext.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/bootstrap.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/KafkaEventCounterService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/kafkaCountingUtil.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/kafka/topic/TopicEventCounterService.kt
Da slipper vi at det forsøkes å opprette nye konsumere med samme groupId.
=> Sørger for å gjenbruke kafka-konsumerene som brukes til telling av eventer

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/bootstrap.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/health/HealthService.kt
Appen trenger ikke lengre å kjøre periodiske metrikker som standard.
De periodiske metrikkene har blitt flyttet ut i en egen app `dittnav-periodic-metrics-reporter`. I det den nye appen har tatt helt over skal all kode for periodiske metrikker fjernes fra aggregatoren.
=> Ikke rapporter periodiske metrikker som standard

src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/ConsumerTestIT.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/Consumer.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/ConsumerTest.kt
Vi vil igjen gjøre rollback av offset i stedet for å stoppe polling for retriable exceptions.
=> Revert "Ønsker midlertidig at all polling stoppes ved alle typer feil."

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/Consumer.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/ConsumerTest.kt
Dette er nyttig i bla tester for å slippe det å legge til vente-steg for å vente på at pollingen skal returnere data.
=> Har gjort tiden det ventes på data per poll, mot Kafka, konfigurerbart

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/ProducerNameResolver.kt
Slik at det blir lettere å se hvilket alias det faktisk mangler mapping for.
=> Logger navnet på eventuelle systembrukere det ikke blir funnet alias for

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/ProducerNameResolver.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/ProducerNameResolverTest.kt
* Logger på info-nivå for forventede oppdateringer av cache.
* Logger kun på warning-nivå hvis en systembruker verken ble funnet i cache-en eller databasen.
=> Justert logging rundt oppslag på mapping for systembrukere

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/ApplicationContext.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/metricsProbeSetup.kt
Dette er viktig siden hver name-scrubber-en har en cache, og denne cache-en ønsker vi bare en versjon av. For å oppdatere cache-en må det gjøres et database-kall, og dette behovet har nå blitt halvert.
=> Sørger for at samme name scrubber brukes i hele appen

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/EventMetricsSession.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveEventService.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/EventMetricsSessionTest.kt
Dette gjør at vi slipper å få alarmer i Slack på dette, fram til produsenten har sluttet å sende duplikater.
=> Senker midlertidig loggnivået for duplikat-advarsler fra en spesifikk produsent som sender mye duplikater

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Kafka.kt
Denne svelger og logger serializationerrors, slik at eventer som ikke lar seg deserialisere ikke skal lage en propp.
Har testet lokalt i docker-compose og i dev, og det ser ut som det fungerer fint. Noen som har innspill til ytterligere enhetstester av dette? Det finnes allerede tester for denne serializeren, som vi av en uviss grunn har skrevet, men ikke tatt i bruk (?).
=> Bytter til en egen avrodeserializer 

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Oppgraderte til Gradle 6.6.1, som er strengere enn tidligere versjoner. Dette førte til at det kom noen nye warnings, bla at det ikke er lov med duplikater av filer i JAR-filer. Har gjort justeringer i build.gradle.kts for å imøtekomme dette.
Har verifisert at denne branch-en kan startes både på Nais i Q1 og i docker-compose.
=> Retter feil som gjorde at appen ikke startet i Docker

init.sh
Dette hindrer at vi overskriver med en tom verdi hvis pathen ikke eksisterer. Dermed kan vi også slippe mountingen av dette i docker-compose.
=> Init-scriptet setter ikke verdi for systembruker-variabler hvis allerede satt

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Kafka.kt
* Revert-er økningen av `default.api.timeout.ms`. Timeout-en oppstår fordi broker-en re-balanseres etter at den har markert en konsument som død. Dette kan skje hvis det tar for lang tid å prosessere done-eventer.
* Fjerner ubrukt import av KafkaAvroDeserializer
=> Revert-er økningen av default.api.timeout.ms

build.gradle.kts, buildSrc/build.gradle.kts, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/util/KafkaConsumerUtil.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/util/KafkaProducerUtil.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/kafkaConsumer.kt
Har løfte alle avhengigheter unntatt Kluent og Mockk, fordi de hadde mange api-edringer. Venter derfor med å endre disse, slik at vi ser sikre på at testene fungerer som før.
Det er lettere å lese denne PR-en ved å deaktivere [visning av whitespace-endringer](https://github.com/navikt/dittnav-event-aggregator/pull/125/files?diff=unified&w=1).
=> Løftet alle avhengigheter, unntatt Kluent og Mockk

buildSrc/build.gradle.kts, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/EndToEndTestIT.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTeardownQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/beskjedQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/AvroBasicKafkaEmbeddedTesting.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/StringBasicKafkaEmbeddedTesting.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/consumer/MultipleTopicsConsumerTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/consumer/SingleTopicConsumerTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/innboksQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/oppgaveQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/StatusoppdateringQueriesTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/StatusoppdateringTeardownQueriesTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/ConsumerTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/serializer/SwallowSerializationErrorsAvroDeserializerTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/logging/MaskedLoggingEventTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/DBMetricsProbeTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/EventMetricsProbeTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/ProducerNameResolverTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/ProducerNameScrubberTest.kt
Oppgradert til ny versjon av `dittnav-dependencies`, som inneholder ny versjon av Kluent.
Fjernet alle nye warnings som kom til pga at enkelte metoder i Kluent hadde blitt deprecated.
=> Tatt i bruk ny versjon av Kluent

buildSrc/build.gradle.kts
Oppgradert til ny versjon av `dittnav-dependencies`, som inneholder ny versjon av `Mockk`.
Har oppgradert til det som på Github er marker som siste release-versjon av Mockk. Det finnes to nyere tags, men ved bruk av disse er det flere av våre tester som ikke fungerer slik de skal.
=> Oppgradert til nye versjon av `Mockk`

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/Consumer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/ApplicationContext.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/bootstrap.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/health/HealthService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/polling/PeriodicDoneEventWaitingTableProcessor.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/polling/pollingApi.kt
Dette er en rask og naiv implementasjon av denne featuren, og har ikke all funksjonalitet som vi ønsker på sikt.
Hvis det blir funnet at minst en konsumer ikke kjører, så restartes de. Gjenbruker samme logikk som om konsumerne hadde blitt restartet manuelt via REST.
Sjekken kjøres hvert 30. minutt, etter at appen har blitt startet.
Har i tillegg reaktivert at det polles etter eventer med en gang appen starter.
=> Periodisk sjekk som ser om alle kafka-konsumerne kjører

build.gradle.kts, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/Beskjed.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/exceptions/FieldValidationException.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/validation/validationUtil.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/Done.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/Innboks.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksTransformer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/Oppgave.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveTransformer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/Statusoppdatering.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/StatusoppdateringEventService.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTransformerTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneTransformerTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksTransformerTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveTransformerTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/AvroStatusoppdateringObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/StatusoppdateringObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/StatusoppdateringTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/statusoppdatering/StatusoppdateringTransformerTest.kt
All validering av event-typene fra Kafka skjer gjennom repo brukernotifikasjon-schemas. Dette betyr at vi kun trenger å endre i brukernotifikasjon-schemas hvis valideringskrav endrer seg.
Dette hører sammen med [PR-en](https://github.com/navikt/brukernotifikasjon-schemas/pull/19) som ligger i brukernotifikasjon-schemas.
=> Valider alle event som kommer inn fra Kafka med brukernotifikasjon-schemas

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedEventService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Environment.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveEventService.kt
Dette er et midlertidig tiltak, og siste steg før vi merger navikt/brukernotifikasjon-schemas#19 til main.
=> Logger melding på Error-nivå hvis event med eksternvarsling = true finnes i prod.

buildSrc/build.gradle.kts, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/EndToEndTestIT.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/config/KafkaEmbed.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/consumer/MultipleTopicsConsumerTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/consumer/SingleTopicConsumerTest.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/kafka/util/KafkaTestUtil.kt, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/ConsumerTestIT.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Environment.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Kafka.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/KafkaConsumerSetup.kt
Sentraliserer `isCurrentlyRunningOnNais`-sjekken, og henter kun variabler knyttet til sikkerhet ved behov.
La til nye variabler i dittnav-dependencies, og gjorde en liten tilpasning rundt db-host og portnummer, slik at det igjen skal være mulig å kjøre aggregator lokalt.
=> Restrukturerte config for å få mer kontroll over når variabler knyttet til sikkerhet bør hentes.

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/kafka/Consumer.kt
Dette logginnslaget blir trigget annenhvert sekund av appens readiness-sjekk, selv om selve denne sjekken ikke blir regnet med i readiness-statusen for appen. Dette er ikke noe vi trenger å agere på, og kan derfor logges på info-nivå. Appens coroutine med `PeriodicConsumerPollingCheck` vil hver halvtime sørge for å restarte consumere som har stoppet. Gjorde dette også tydligere i selve logginnslaget.
=> Fjernet unødvendig error-logging

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/config/Kafka.kt
Dette gjør at den leser fra starten igjen etter groupid har blitt endret, slik det er meningen.
=> Set AUTO_OFFSET_RESET_CONFIG til "earliest".

buildSrc/build.gradle.kts, src/intTest/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/LocalPostgresDatabase.kt
Oppdatert testcontainer, og legg inn flyway-retry for få intergrasjonstester til å fungere på m1-mac med colima.
Det tar litt lenger tid å starte opp testcontainter, usikker på om det er pga m1-macen eller colima, så flyway må prøve et par ganger
=> Gjøre integrasjonstestene m1/colima compliant

nais/prod-gcp/nais.yaml
Gir oss flere resurser for brukernotifikasjon-cache (4 cpu 24GB) for å tilnærme det vi har on-prem i dag (8 cpu og 32GB).
=> Dobler db-resurser i prod.

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneRepository.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/doneQueries.kt
Hensikten med dette er å løse et tilfelle vi har der gamle done-eventer i ventetabellen Disse finner aldri match, og sperrer for nye done-eventer som da aldri blir behandlet.
I gcp er dette løst ved å rotere på hvilke eventer som blir behandlet.
=> Øker antall done eventer som hentes fra ventetabellen, og sorterer dem etter nyeste først.

src/main/resources/db/migration/V1.1.15__Legger_til_felt_behandlet.sql, src/main/resources/db/migration/V1.1.16__Legger_paa_indekser_eventtidspunkt.sql
Fortsettelse av https://github.com/navikt/dittnav-event-aggregator/pull/179
Denne feilet ved deploy pga Flyway-kjøring som tok svært lang tid. Fjerner disse spørringene, som var egentlig er unødvendige. Dette håndteres i kode ved ny innlesing til cachen. Har kjørt dette manuelt utenom Flyway for cachen nå. 
Indeksene som blir lagt på er egentlig unødvendige, men det gjør jo ingen skade om de er der. De har allerede blitt kjørt av Flyway.
=> Felt for forstBehandlet

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusDto.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusRepository.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusService.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusUpdater.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotofikasjonStatusTransformer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/UpdateStatusResult.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/doknotifikasjonStatusQuery.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/metrics/DoknotifikasjonStatusMetricsProbe.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/metrics/DoknotifikasjonStatusMetricsSession.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/metrics/metricNames.kt, src/main/resources/db/migration/V1.1.26__Doknotiikasjon_status_kanaler.sql, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusDtoObjectMother.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusQueryTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusServiceTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusUpdaterTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotofikasjonStatusTransformerTest.kt
Legger til naiv parsing av brukt kanal for ekstern varsling. 
Endrer og flytter også litt på logikken rundt oppdatering av status. "uendret" forsvinner som konsept, og alle oppdateringer vil øke feltet "antall_oppdateringer", selv når alle andre felt forble det samme.
=> Legg til parsing og lagring av kanal der esktern varsel ble sendt.

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/archive/PeriodicBeskjedArchiver.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/archive/beskjedArchivingQueries.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/beskjedQueries.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/LocalDateTimeHelper.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/archive/PeriodicInnboksArchiver.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/archive/innboksArchivingQueries.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/archive/PeriodicOppgaveArchiver.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/archive/oppgaveArchivingQueries.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/oppgaveQueries.kt, src/main/resources/db/migration/V1.1.28__Index_forstBehandlet.sql
Slik det er i dag gjør vi en full table scan hver gang det ikke finnes nok eventer eldre enn x dato.
=> Legger til indekser på forstBehandlet og modifiserer arkiveringsspørringer for å treffe dem.

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/entity/Brukernotifikasjon.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/entity/BrukernotifikasjonTest.kt
Dette forhindrer tilfeller der done ikke matches fordi bruker har flere ID-er.
=> Matcher kun på eventId ved behandling av done.

src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/database/queryUtil.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusDto.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusEnum.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternStatusOppdatering.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingOppdatertProducer.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatus.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatusRepository.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatusSink.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatusUpdater.kt, src/main/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/eksternVarslingStatusQueries.kt, src/main/resources/db/migration/V1.1.33__Endre_doknotifikasjon_status.sql, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/archive/PeriodicVarselArchiverTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedQueriesTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/BeskjedTestData.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/beskjed/testBeskjedQueries.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/common/LocalDateTimeTestHelper.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/DoknotifikasjonStatusDtoTestData.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatusSinkTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/EksternVarslingStatusTestData.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/doknotifikasjon/testDoknotifikasjonStatusQueries.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/done/DoneTestData.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/expired/PeriodicExpiredVarselProcessorTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/InnboksTestData.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/innboks/testInnboksQueries.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveQueriesTest.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/OppgaveTestData.kt, src/test/kotlin/no/nav/personbruker/dittnav/eventaggregator/oppgave/testOppgaveQueries.kt
Endrer internt navn på doknotifikasjon status til ekstern varsling status, og bruker interne navn på statuser. Beholder historikk for tidligere statuser.
Bedømmer status dreier seg om renotifikasjon. Dette er basert på historikk som vi ikke har tatt vare på før nå. For tidligere varsler, og varsler sendt i en overgangsperiode, vil en ikke kunne se om det var renotifikasjon eller ikke.
=> Legger til historikk for ekstern varsling og info om renotifikasjon.
